### ISSUE TITLE
Go install not working

### ISSUE THREAD

**Issue by Kapeli** [technosophos/dashing#1]
I'm probably doing something wrong...

What I did:
1. Install Go from https://golang.org/dl/
2. Run "go install gitub.com/technosophos/dashing" in Terminal
3. Got this error:

```
can't load package: package http:/gitub.com/technosophos/dashing: cannot find package "http:/gitub.com/technosophos/dashing" in any of:
	/usr/local/go/src/http:/gitub.com/technosophos/dashing (from $GOROOT)
	/Users/bogdan/Desktop/go/src/http:/gitub.com/technosophos/dashing (from $GOPATH)
```

Is this supposed to work this way? If I need to do something extra, can you provide install instructions for someone that has never used Go before?

**Comment by technosophos** [comment]
Ugh, this is what I get for skimping on the installation instructions. Sorry about that. It should have said "run `go get -u gitub.com/technosophos/dashing`"

I have both updated the installation instructions and made a binary release available.

Here's the GitHub release page:
https://github.com/technosophos/dashing/releases/tag/0.0.1

**Comment by Kapeli** [comment]
Getting this now:

```
package gitub.com/technosophos/dashing: unrecognized import path "gitub.com/technosophos/dashing"
```

**Comment by florinpatrascu** [comment]
try `go get -u github.com/technosophos/dashing`; `gitub`, was misspelled. HTH

**Comment by Kapeli** [comment]
It works after fixing the misspell. @technosophos please fix the misspell in the README when you can.

**Comment by technosophos** [comment]
It must be a Monday. *sigh*

README is updated.
