### ISSUE TITLE
Issue using pre-built OSX binary or using dashing from terminal after built with Go

### ISSUE THREAD

**Issue by jjstrat3** [technosophos/dashing#18]
I've been unable to figure out how to run dashing from one of the pre-built OSX binaries that you offer with each release.  I guess maybe I'm newbie with this stuff, but the binary doesn't have any sort of extension(.pkg, .dmg?), so I'm confused as to how I'd install it?

With the Go method of building the binary, I've installed Go and ran `go get -u github.com/technosophos/dashing` from my terminal.  While it is located in the correct place in terms of where I set my `$GOPATH` to, trying to run dashing in a new terminal session after the new installation via `dashing create` results in my shell(I use zsh) saying `command not found: dashing`.

What am I doing wrong??

**Comment by technosophos** [comment]
The prebuilt binaries are just executables. If you download them, you can run them directly without extracting anything: `./dashing --help`. Installing it would be a matter of copying it to `/usr/local/bin` (or wherever you wanted it).

If you install with `go get -u`, that will put the binary in `$GOPATH/bin/dashing`, not on `$PATH`. So you'd execute it like this: `$GOPATH/bin/dashing --help`.

I suppose I should see about just putting Dashing in Homebrew or something.

**Comment by jjstrat3** [comment]
@technosophos Ah, yea that makes sense.  The readme just threw me off a little bit since it sort of implied that I should just be able type `$ dashing create` into the terminal after install.
