### ISSUE TITLE
YUIDoc Support -- No CSS?

### ISSUE THREAD

**Issue by alexlafroscia** [technosophos/dashing#2]
I'm giving this a shot, trying to put some docs that I created with YUIDoc into Dash.  However, Dashing doesn't seem to copy CSS files over so things look all wrong.  Does it not do that on purpose?

**Comment by technosophos** [comment]
Oh, that should be a pretty easy fix. I'll add that. Thanks!

**Comment by technosophos** [comment]
If you don't mind, can you give `master` a try, and see if that fixes it? If you'd like me to save you some time and upload a new binary build, let me know.

**Comment by alexlafroscia** [comment]
Nope, that didn't do it.  The contents of the `asserts` directory within `Contents/Resources/Documents` only has an `index.html` file and a `vendor` file, while the source directory has those two, plus a `js`, `img` and `css` directory that seem to have been ignored.

**Comment by technosophos** [comment]
Okay. I'll look again.

**Comment by technosophos** [comment]
Okay, I updated it to copy all of the files in a subdirectory except for (currently) `.git` archives. I'd like to add an `--exclude` flag, but for now, your issue should be resolved.

I tested by creating a set of HTML documents with a css/ directory that contained CSS files. This version now copies not just the HTML document, but all supporting directories and files.

Let me know how it works for you. I'm wondering if in some cases we might need to munge the paths to get the CSS files to load correctly.

**Comment by alexlafroscia** [comment]
Does it look recursively for directories? Because in my case, the `index.html` file is in the directory `docs/`, but the CSS files are in `docs/assets/css`.  It still only seemed to copy the `docs/assets/vendor` directory, the `css` and `js` directories in `docs/assets` are being ignored.

**Comment by technosophos** [comment]
Are you running dashing from inside of docs or from the directory above docs?

**Comment by technosophos** [comment]
After more testing locally, I pushed up the changes I made to `examples/busybox`. For me, if I run `dashing` inside of `examples/busybox`, I see `assets/css/busybox.css` copied into the docset. Is that what you see when you run the test?

**Comment by alexlafroscia** [comment]
Nope. I pulled the latest, did
```
cd examples/busybox`
dashing build
cd busybox.docset/Contents/Resources/Documents
```
and the contents were only the `BusyBox.html` file

**Comment by technosophos** [comment]
Did you do a new `go build dashing.go`?

On Tue, Aug 4, 2015 at 3:12 PM, Alex LaFroscia <notifications@github.com>
wrote:

> Nope. I pulled the latest, did
>
> cd examples/busybox`
> dashing build
> cd busybox.docset/Contents/Resources/Documents
>
> and the contents were only the BusyBox.html file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/technosophos/dashing/issues/2#issuecomment-127763488>.
>



-- 
http://technosophos.com
https://github.com/Masterminds

**Comment by alexlafroscia** [comment]
Oh no, I didn't... Didn't realize I needed to. I'm new at Go :stuck_out_tongue_closed_eyes:
