### ISSUE TITLE
Homebrew formula?

### ISSUE THREAD

**Issue by ylluminarious** [technosophos/dashing#33]
This project looks really useful and it'd be nice to have convenient installation through a homebrew formula. I guess you thought about doing this [in the past](https://github.com/technosophos/dashing/issues/18#issuecomment-172599158) and I think it's a really great idea.

**Comment by ylluminarious** [comment]
@technosophos Well, I went ahead and [made a PR](https://github.com/Homebrew/homebrew-core/pull/23696) to homebrew-core.

**Comment by ylluminarious** [comment]
@technosophos Looks like [we got it merged!](https://github.com/Homebrew/homebrew-core/pull/24046) So I'll go ahead and close this.

**Comment by technosophos** [comment]
That is awesome. Thank you.

**Comment by ylluminarious** [comment]
@technosophos You're welcome! And thank you for making this useful tool! Please also see #35 so that we can let other users know that this program is available in Homebrew now.
