### ISSUE TITLE
can't handle section names with slashes `/` inside

### ISSUE THREAD

**Issue by cvogt** [technosophos/dashing#5]
I configured dashing to convert h1 into sections. If they contain `/` in the text, no sections are generated, but broken "Unknown" entries instead. They can only be seen in the sections pane on the lower left of dash, when on the corresponding page.

**Comment by technosophos** [comment]
Can you give me a snippet of HTML to test with? I'll take a look.

**Comment by technosophos** [comment]
Any update? I can't reproduce the problem, probably because I'm doing it wrong. But I'd like to get a new release out soon, and I'd love to have this issue fixed.

**Comment by cvogt** [comment]
This snippet for example
```html<span id="index-11"></span><h3>Scalar value subquery / custom function<a class="headerlink" href="sql-to-slick.html#scalar-value-subquery-custom-function" title="Permalink to this headline">¶</a></h3>
`

**Comment by cvogt** [comment]
The problem seems to be that the `/` is not escaped properly in `//apple_ref/cpp/Section/Scalar%20value%20subquery%20/%20custom%20function%C2%B6`

**Comment by cvogt** [comment]
looks like it needs url escaping applied here: https://github.com/technosophos/dashing/blob/dbdc145e031b1351175a273e7010baab6f8e14e6/dashing.go#L411

**Comment by technosophos** [comment]
Names are now encoded with net/url.QueryEscape.

**Comment by technosophos** [comment]
And thanks for making it super easy to fix.

**Comment by cvogt** [comment]
thank you for fixing it so quickly :)!
