### ISSUE TITLE
Fix homebrew formula

### ISSUE THREAD

**Issue by iwittkau** [technosophos/dashing#54]
Hi,

building dashing from source is currently broken in homebrew:

```
brew install --build-from-source dashing
==> Installing dependencies for dashing: glide
==> Installing dashing dependency: glide
==> Downloading https://homebrew.bintray.com/bottles/glide-0.13.3.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/79/795f7f533f050b5356846b3ed2a9db88a51ef74b929e28ea0473c83f630b03c3?__gd
######################################################################## 100.0%
==> Pouring glide-0.13.3.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/glide/0.13.3: 6 files, 12.1MB
==> Installing dashing
==> Downloading https://github.com/technosophos/dashing/archive/0.3.0.tar.gz
==> Downloading from https://codeload.github.com/technosophos/dashing/tar.gz/0.3.0
######################################################################## 100.0%
==> glide install
Last 15 lines from /Users/iwittkau/Library/Logs/Homebrew/dashing/01.glide:
glide
install

[INFO]	Lock file (glide.lock) does not exist. Performing update.
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching gopkg.in/yaml.v2
[INFO]	--> Fetching github.com/codegangsta/cli
[INFO]	--> Fetching github.com/mattn/go-sqlite3
[INFO]	--> Fetching golang.org/x/net
[INFO]	--> Fetching github.com/andybalholm/cascadia
[INFO]	Resolving imports
[INFO]	--> Fetching github.com/cpuguy83/go-md2man
[ERROR]	Error scanning github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "." in:
	/Users/iwittkau/Library/Caches/Homebrew/glide_home/dashing/cache/src/https-github.com-cpuguy83-go-md2man/v2/md2man
[ERROR]	Failed to retrieve a list of dependencies: Error resolving imports
```

Looks like `github.com/cpuguy83/go-md2man/v2/md2man` isn't available anymore.

Can you please fix your glide dependencies? Without a fix of the dashing formula we won't be able to merge https://github.com/Homebrew/homebrew-core/pull/47510 and update the go formula to 1.13.5.

I already tried to fix another error here: https://github.com/Homebrew/homebrew-core/pull/47842 but that didn't fix the broken glide build process of course.

**Comment by iwittkau** [comment]
https://github.com/technosophos/dashing/pull/53 might resolve this

**Comment by amake** [comment]
> Looks like `github.com/cpuguy83/go-md2man/v2/md2man` isn't available anymore.

It's not that it's not available; it's that it uses a modern [go module major version](https://github.com/golang/go/wiki/Modules#faqs--semantic-import-versioning) that glide doesn't understand.

**Comment by iwittkau** [comment]
Ok, looks like only #53 can really fix this then.

**Comment by technosophos** [comment]
Should be fixed by #53

**Comment by iwittkau** [comment]
@technosophos thanks! Can you tag a new version, so we can use it in homebrew?

**Comment by iwittkau** [comment]
Also, the test download `https://ruby-doc.org/downloads/ruby_2_5_0_core_rdocs.tgz` seems flaky. The sha sum changed recently and now I get a 403 when I try to download it.

**Comment by technosophos** [comment]
Okay, the 0.4.0 tag is cut. I will have to take a bit more time to look at the flaky test
