### ISSUE TITLE
Trim parsed contents

### ISSUE THREAD

**Issue by pochemuto** [technosophos/dashing#6]
Often content in selector has spaces that not needed. 
For example, in Oracle documentation error codes declared as:
```html
<span class="msg">
<a id="sthref1939"></a> ORA-04930: open sequence number failed or initial state is valid
</span>
```
So in Dash I have error codes with leading space: " ORA-04930: ...".

![2015-09-11 15 47 06](https://cloud.githubusercontent.com/assets/690543/9815128/64c07778-589c-11e5-863a-415d82bcde37.png)

**Comment by technosophos** [comment]
I have fixed this in the code (I think). Are you comfortable building from source and testing, or would you rather a binary release?

**Comment by pochemuto** [comment]
I think I can compile. Now I use binary release, but I hope there will not
be problems with building from source.

пятница, 11 сентября 2015 г. пользователь Matt Butcher написал:

**Comment by pochemuto** [comment]
I have tested version builded from sources. It trims spaces correctly. Thanks!

**Comment by technosophos** [comment]
Thanks!
