### ISSUE TITLE
dashing generating an empty docset

### ISSUE THREAD

**Issue by allenjhyang** [technosophos/dashing#64]
I'm playing with dashing to generate a docset automatically for this URL: https://www.lusternia.com/local/webolc/manual.html#idm154

Here's my dashing.json:
```
{
    "name": "Lusternia Prog",
    "package": "lusterniaprog",
    "index": "index.html",
    "selectors": {
        "title": "Package",
        "h2": "Section",
        "h3": "Class",
        "span.glossterm": "Command"
    },
    "ignore": [
        "Introduction"
    ],
    "icon32x32": "lusternia_favicon.jpeg",
    "allowJS": false,
    "ExternalURL": "https://www.lusternia.com/local/webolc/manual.html"
}
```

When I run `dashing build lusterniaprog`, it creates a lusterniaprog.docset file in the directory, but it appears to be empty when loaded into Dash. Am I misunderstanding something about how this works?

**Comment by BryceStevenWilley** [comment]
Dashing assumes that the HTML documentation is downloaded locally on your machine already, and that you are running dashing from the same directly that the docs are in.

For your example, you would download `manual.html` and `ire_online_help.css` from https://www.lusternia.com/local/webolc/, change `"index": "index.html"` in your `dashing.json` to `"index": "manual.html"`, and then run dashing.

**Comment by allenjhyang** [comment]
Ah yep, that does it. Thanks for clarifying!
