### ISSUE TITLE
dashing no longer builds

### ISSUE THREAD

**Issue by foozmeat** [technosophos/dashing#65]
It's not possible to build dashing at the moment.I'm not a go user so I don't know what the issue could be. Perhaps a broken dependency? 

```
root@2f9a633263bc:/go# go get -u github.com/technosophos/dashing
package github.com/urfave/cli/v2: cannot find package "github.com/urfave/cli/v2" in any of:
        /usr/local/go/src/github.com/urfave/cli/v2 (from $GOROOT)
        /go/src/github.com/urfave/cli/v2 (from $GOPATH)
```

**Comment by rrrix** [comment]
Make sure you're using a recent version of go (`go>=1.18`), then try:

```
go install github.com/technosophos/dashing@latest
```

To properly troubleshoot your error, you should post a bit more information on your environment:

- OS / OS Release / OS Version 
	- `uname -a`
	- `lsb_release` on Linux or `sw_vers` on macOS
- The output from `go env`
