### ISSUE TITLE
Messy titles

### ISSUE THREAD

**Issue by cvogt** [technosophos/dashing#8]
I am mirroring websites and turning them into dash docs using dashing. I also had problems with websites ending headings with `¶` (e.g. http://slick.typesafe.com/doc/3.0.3/) or starting them with `§` (e.g. https://www.playframework.com/documentation/2.4.x/Highlights24) or putting the name of the site into the <title> tag first (e.g. http://spray.io/documentation/1.2.3/). Is there any way to clean them up? Maybe an option to detect and strip a common prefix from all elements of a certain selector would be nice.

I also had problems with websites using the same heading in their menu on every page. Sometimes tags alone aren't enough to filter them out. I can't use css selectors, right? Ignoring them each works for is very fragile against changes.

**Comment by technosophos** [comment]
You should be able to use full CSS3 selectors. Dashing uses an upstream CSS selectors package, but if you find anything missing I will gladly patch the upstream repo.

That said, I'm going to see if i can figure out another way of processing some of this data. It might be possible to provide some sort of template-y interface to allow you a chance to munge things.

**Comment by cvogt** [comment]
I think allowing to give a prefix or suffix that is stripped would already cover most of the cases and it would be a very simple solution.

**Comment by cvogt** [comment]
or a regex replacement pattern for more flexibility

**Comment by technosophos** [comment]
A regexp replace is a great idea. I'm going to try that.

**Comment by cvogt** [comment]
If you use ReplaceAllString (https://golang.org/pkg/regexp/#Regexp.ReplaceAllString) and let users provide the `re` and `repl` arguments via config, that should do it. Would be nice to provide such a replacement for each selector.

**Comment by technosophos** [comment]
A sample of usage is in the Busybox example. Basically, instead of supplying:

```
"h1": "Command"
```
 you can now do:

```
"h1": {
  "type":"Command",
  "regexp": "foo*",
  "replacement": "bar"
}
```

I used ReplaceAllString, so you can use backreferences.

Let me know how it works out.

**Comment by cvogt** [comment]
Works great! Thx so much. I could see myself potentially running into needing multiple of such replacements per element, but not yet :).

**Comment by cvogt** [comment]
fixed
